//export let SERVER_URL = 'http://retime-dev.herokuapp.com/';  
export let SERVER_URL = 'http://192.168.100.3:3000/';
export let SESSION_KEY = '';
export let EMAIL_REGEXP = /^[a-z0-9!#$%&'*+\/=?^_`{|}~.-]+@[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i;
export let MESSAGE = 'Please wait...';
export let ERROR = 'SOMETHING WENT WRONG.';
export let NO_DATA_FOUND = 'Sorry! No Data Found.'
export let STUDY_START_TOAST = 'New Study has started';
export let NOTES_ALERT_TITLE = "STUDY NOTES";
export let NOTES_ALERT_MESSAGE = "Please enter some notes for this Study.";
export let FILE_UPLOADED_MESSAGE = "Study Photo uploaded successfully.";
export let FILE_SAVED_LOCALLY = "Study Photo saved successfully in local data base and will be synced when Internet is available."
export let OFFLINE_STUDY_DATA_MSG = "Study Data will be saved when internet is available."
export let INTERNET_ERROR = "Sorry! No Internet connection available right now."
export let SYNC_DONE = "All the data synced successfully.";
export let SYNC_DATA_MSG = 'Syncing Data...';
export let STUDY_CANCELING_MESSAGE = 'Are you sure that you want to cancel this Study ?'
export let ALERT_TITLE = "Efficiency Study";
export let BACK_BTN_MESSAGE= "Press back again to exit the App.";
export let REMOVING_STUDY_ITEMS_MSG = "Are you sure that you want to remove all Study Itmes ?";
export let ROUND_ENDED = "Round has now ended";
export let STUDY_ENDED = "Study has now ended";
export let DELETE_TITLE = 'Delete Item';
export let DELETE_MSG = 'Are you sure that you want to delete this Item ?';
export let FREQUENCY_INPUT_ERROR = "Only positive numbers are allowed";
export let ENTRY_ALREADY_EXIST = "An entry with the same name already exists."
export let SESSION_EXPIRED = "Please login again.";
